### ISSUE TITLE
Open to contributions?

### ISSUE THREAD

**Issue by SaileshBK** [Guy-S-glitch/BombRocketGame#31]

**Comment by Guy-S-glitch** [comment]
hi saileshBK. i didn't really understand your request if you would like to get access for this project or maybe you meant to ask in general if i'm open to working on a new project. however thanks for your comment, i'm open for contributions and i'll do your request the moment you'll comment back.

**Comment by SaileshBK** [comment]
Hi I meant I really like the concept of this project and I want to help improve this project, If you guys need help if this project is Open Source? I can start making pull requests on few things I noticed :)

**Comment by Guy-S-glitch** [comment]
sure that's sound great.

**Comment by SaileshBK** [comment]
we should start creating issues that you have in mind that you want to implement. I will do the same when I get the chance.

**Comment by Guy-S-glitch** [comment]
i'll follow your pr. it is my first project and i'm not really experience with github but i'll do my best giving you issues

**Comment by SaileshBK** [comment]
Sounds Good :)
